[package]
name = "chronicle-cli"
publish.workspace = true
repository.workspace = true
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[[bin]]
name = "chronicle"
path = "src/main.rs"

[dependencies]
chronicle-application = { path = "../chronicle-application" }
chronicle-common = { path = "../chronicle-common" }
chronicle-protocol = { path = "../chronicle-protocol" }
chronicle-replay = { path = "../chronicle-replay" }
clap.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
tracing-subscriber.workspace = true
uuid.workspace = true

[lints]
workspace = true
