[package]
name = "chronicle-cli"
publish.workspace = true
repository.workspace = true
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[[bin]]
name = "chronicle"
path = "src/main.rs"

[features]
default = []
linux-ebpf = ["chronicle-application/linux-ebpf", "tokio/signal"]

[dependencies]
chronicle-application = { path = "../chronicle-application" }
chronicle-common = { path = "../chronicle-common" }
chronicle-protocol = { path = "../chronicle-protocol" }
chronicle-protocol-builtins = { path = "../chronicle-protocol-builtins" }
chronicle-replay = { path = "../chronicle-replay" }
clap.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
tracing-subscriber.workspace = true
uuid.workspace = true

[dev-dependencies]
chronicle-capture = { path = "../chronicle-capture" }
chronicle-wal = { path = "../chronicle-wal" }
rustix.workspace = true

[lints]
workspace = true
