[package]
name = "chronicle-replay"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
chronicle-canonical = { path = "../chronicle-canonical" }
chronicle-common = { path = "../chronicle-common" }
chronicle-protocol = { path = "../chronicle-protocol" }
thiserror.workspace = true

[dev-dependencies]
time.workspace = true
tokio.workspace = true

[lints]
workspace = true
