[package]
name = "chronicle-canonical"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
chronicle-common = { path = "../chronicle-common" }
serde.workspace = true
time.workspace = true

[dev-dependencies]
serde_json.workspace = true

[lints]
workspace = true
