[package]
name = "chronicle-application"
publish.workspace = true
repository.workspace = true
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
chronicle-canonical = { path = "../chronicle-canonical" }
chronicle-capture = { path = "../chronicle-capture" }
chronicle-common = { path = "../chronicle-common" }
chronicle-etl = { path = "../chronicle-etl" }
chronicle-protocol = { path = "../chronicle-protocol" }
chronicle-protocol-builtins = { path = "../chronicle-protocol-builtins" }
chronicle-replay = { path = "../chronicle-replay" }
chronicle-session = { path = "../chronicle-session" }
chronicle-storage = { path = "../chronicle-storage" }
chronicle-wal = { path = "../chronicle-wal" }
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
time.workspace = true
tokio.workspace = true
toml.workspace = true
uuid.workspace = true

[lints]
workspace = true
